package sitemap

import (
	"fmt"
	"strings"
)

type RobotsRule struct {
	UserAgent  string   `json:"user_agent"`
	Allow      []string `json:"allow,omitempty"`
	Disallow   []string `json:"disallow,omitempty"`
	CrawlDelay *int     `json:"crawl_delay,omitempty"`
}

type RobotsRequest struct {
	Rules           []RobotsRule `json:"rules"`
	Sitemaps        []string     `json:"sitemaps,omitempty"`
	Host            string       `json:"host,omitempty"`
	IncludeComments bool         `json:"include_comments,omitempty"`
}

func GenerateRobots(req *RobotsRequest) ([]byte, error) {
	if len(req.Rules) == 0 {
		return nil, fmt.Errorf("at least one rule is required")
	}

	var sb strings.Builder

	if req.IncludeComments {
		sb.WriteString("# robots.txt generated by Sr-gA\n")
		sb.WriteString("# https://github.com/Normious/Sr-gA\n\n")
	}

	for i, rule := range req.Rules {
		if rule.UserAgent == "" {
			return nil, fmt.Errorf("rule %d: user_agent is required", i)
		}

		sb.WriteString(fmt.Sprintf("User-agent: %s\n", rule.UserAgent))

		for _, allow := range rule.Allow {
			sb.WriteString(fmt.Sprintf("Allow: %s\n", allow))
		}
		for _, disallow := range rule.Disallow {
			sb.WriteString(fmt.Sprintf("Disallow: %s\n", disallow))
		}
		if rule.CrawlDelay != nil {
			sb.WriteString(fmt.Sprintf("Crawl-delay: %d\n", *rule.CrawlDelay))
		}

		sb.WriteString("\n")
	}

	for _, sitemap := range req.Sitemaps {
		sb.WriteString(fmt.Sprintf("Sitemap: %s\n", sitemap))
	}

	if req.Host != "" {
		sb.WriteString(fmt.Sprintf("Host: %s\n", req.Host))
	}

	return []byte(sb.String()), nil
}
